/*
 * ext_interrupt_cfg.h
 *
 * Created: 11/11/2020 11:34:21 PM
 *  Author: 20111
 */ 


#ifndef EXT_INTERRUPT_CFG_H_
#define EXT_INTERRUPT_CFG_H_

#define	GLOBAL_INTERRUPT_STATE    GLOBAL_INTERRUPT_ENABLE	
#define EXT_INTERRUPT0_TRIGGER    EXT_INTERRUPT_RAISING_EDGE
#define EXT_INTERRUPT1_TRIGGER	  EXT_INTERRUPT_FALLING_EDGE
#define EXT_INTERRUPT2_TRIGGER	  EXT_INTERRUPT_FALLING_EDGE

#endif /* EXT_INTERRUPT_CFG_H_ */